openapi: 3.0.3
info:
  title: Manipuler les paramètres et réponses
  version: 1.0.0
paths:
  /users:
    get:
      parameters:
        - name: page # - est obligatoire car parameters est une liste
          in: query
          schema:
            type: integer
          example: 1
        - name: size
          in: query
          schema:
            type: integer
          example: 20

           
      responses:
        '200':
          description: succès
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string 
                  email:
                    type: string    
              example:
                id: 1
                name: ALice
                email: alice@gmail.com
        '400':
          description: mauvais type de paramètre fourni
          content:
            application/json:
              schema:
                type: object
                properties:
                  error: 
                    type: string
              example:
                error: "Bad types for provided query parameters"